[mypy]
python_version = 3.11
ignore_missing_imports = True
check_untyped_defs = True
warn_unused_ignores = False
show_error_codes = True
namespace_packages = True
explicit_package_bases = True

[mypy-app.models.*]
ignore_errors = True

[mypy-app.models]
ignore_errors = True

[mypy-app.modules.*]
ignore_errors = True

[mypy-app.core.idempotency]
ignore_errors = True

[mypy-app.core.database]
ignore_errors = True

[mypy-app.seed]
ignore_errors = True

[mypy-app.workers.*]
ignore_errors = True