"""domain_core_tables

Revision ID: 0111b944a435
Revises: 35063b74a70b
Create Date: 2026-08-28 17:14:57.163990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '0111b944a435'
down_revision: Union[str, Sequence[str], None] = '35063b74a70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_marathi', sa.Text(), nullable=True),
    sa.Column('name_hindi', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('markets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_marathi', sa.Text(), nullable=True),
    sa.Column('district', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('location_geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('market_type', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('CREATE INDEX IF NOT EXISTS ix_markets_geog ON markets USING gist (location_geog)')
    op.create_table('match_rulesets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('price_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('adapter', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('storage_facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('available_capacity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location_text', sa.Text(), nullable=True),
    sa.Column('location_geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('cost_per_unit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contact', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.CheckConstraint('available_capacity >= 0 OR available_capacity IS NULL', name='ck_storage_avail'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('CREATE INDEX IF NOT EXISTS idx_storage_facilities_location_geog ON storage_facilities USING gist (location_geog)')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('location_geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('farmer','buyer','fpo','admin','operator')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.execute('CREATE INDEX IF NOT EXISTS idx_users_location_geog ON users USING gist (location_geog)')
    op.create_table('buyer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.Text(), nullable=False),
    sa.Column('business_type', sa.Text(), nullable=True),
    sa.Column('license_number', sa.Text(), nullable=True),
    sa.Column('crops_interested', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('min_quantity_quintals', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_quantity_quintals', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preferred_grade', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=True),
    sa.Column('location_geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.CheckConstraint("business_type IN ('trader','processor','exporter','retailer') OR business_type IS NULL", name='ck_buyer_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.execute('CREATE INDEX IF NOT EXISTS idx_buyer_profiles_location_geog ON buyer_profiles USING gist (location_geog)')
    op.create_table('crop_varieties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop_id', 'name', name='uq_crop_variety')
    )
    op.create_table('farmer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('land_area_acres', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('primary_crops', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('bank_account_encrypted', sa.Text(), nullable=True),
    sa.Column('ifsc_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('fpo_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_name', sa.Text(), nullable=False),
    sa.Column('registration_number', sa.Text(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('total_land_acres', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('primary_crops', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_ok', sa.Integer(), nullable=True),
    sa.Column('records_rejected', sa.Integer(), nullable=True),
    sa.Column('parser_version', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['price_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('related_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('buyer_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=True),
    sa.Column('crop_name', sa.Text(), nullable=False),
    sa.Column('variety_id', sa.UUID(), nullable=True),
    sa.Column('grade', sa.Text(), nullable=True),
    sa.Column('quantity_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location_geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('max_distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('required_from', sa.Date(), nullable=True),
    sa.Column('required_until', sa.Date(), nullable=True),
    sa.Column('delivery_window', sa.Text(), nullable=True),
    sa.Column('storage_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['crop_varieties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('CREATE INDEX IF NOT EXISTS idx_buyer_requirements_location_geog ON buyer_requirements USING gist (location_geog)')
    op.create_table('lots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=True),
    sa.Column('crop_name', sa.Text(), nullable=False),
    sa.Column('variety_id', sa.UUID(), nullable=True),
    sa.Column('grade', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('asking_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('market_reference_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location_text', sa.Text(), nullable=False),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('location_geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('available_until', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("grade IN ('A','B','C')", name='ck_lot_grade'),
    sa.CheckConstraint("status IN ('DRAFT','PUBLISHED','RESERVED','PARTIALLY_ALLOCATED','SOLD','FULFILLED','CANCELLED','EXPIRED','active','matched','sold','expired','cancelled')", name='ck_lot_status'),
    sa.CheckConstraint('quantity > 0', name='ck_lot_qty_pos'),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['crop_varieties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.execute('CREATE INDEX IF NOT EXISTS ix_lots_geog ON lots USING gist (location_geog)')
    op.create_index('ix_lots_owner', 'lots', ['owner_id'], unique=False)
    op.create_index('ix_lots_public_id', 'lots', ['public_id'], unique=False)
    op.create_index('ix_lots_status', 'lots', ['status'], unique=False)
    op.create_table('price_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('variety_id', sa.UUID(), nullable=True),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('modal_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume_tonnes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.Column('parser_version', sa.Text(), nullable=True),
    sa.Column('normalization_version', sa.Text(), nullable=True),
    sa.Column('raw_payload_hash', sa.Text(), nullable=True),
    sa.Column('quality_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.CheckConstraint("quality_status IN ('HIGH','MEDIUM','LOW')", name='ck_quality'),
    sa.CheckConstraint('modal_price > 0', name='ck_modal_positive'),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['price_sources.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['crop_varieties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop_id', 'market_id', 'price_date', 'source_id', name='uq_price_obs')
    )
    op.create_index('ix_price_obs_crop_market_date', 'price_observations', ['crop_id', 'market_id', 'price_date'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('buyer_requirement_id', sa.UUID(), nullable=True),
    sa.Column('ruleset_id', sa.UUID(), nullable=True),
    sa.Column('ruleset_version', sa.Text(), nullable=True),
    sa.Column('component_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('final_score', sa.Integer(), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['buyer_requirement_id'], ['buyer_requirements.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['ruleset_id'], ['match_rulesets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id', 'buyer_id', 'ruleset_version', name='uq_match_lot_buyer_ruleset')
    )
    op.create_index('ix_matches_lot_score', 'matches', ['lot_id', 'final_score'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('parent_offer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.CheckConstraint("status IN ('PENDING','COUNTERED','ACCEPTED','REJECTED','EXPIRED','CANCELLED','pending','accepted','rejected','expired','completed')", name='ck_offer_status'),
    sa.CheckConstraint('quantity > 0', name='ck_offer_qty'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offers_buyer', 'offers', ['buyer_id'], unique=False)
    op.create_index('ix_offers_lot', 'offers', ['lot_id'], unique=False)
    op.create_table('lot_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=True),
    sa.Column('allocated_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fulfilled_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.CheckConstraint('allocated_quantity > 0', name='ck_alloc_qty'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alloc_lot', 'lot_allocations', ['lot_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE','EXPIRED','CONSUMED','CANCELLED')", name='ck_res_status'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('allocation_id', sa.UUID(), nullable=True),
    sa.Column('offer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('gross_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transport_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('storage_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_realization', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.CheckConstraint("status IN ('CREATED','PAYMENT_PENDING','PAYMENT_CONFIRMED','PROCESSING','READY_FOR_DISPATCH','IN_TRANSIT','DELIVERED','COMPLETED','DISPUTED','CANCELLED','REFUNDED','offer_accepted','payment_pending','payment_received','completed')", name='ck_txn_status'),
    sa.ForeignKeyConstraint(['allocation_id'], ['lot_allocations.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_txn_buyer', 'transactions', ['buyer_id'], unique=False)
    op.create_index('ix_txn_seller', 'transactions', ['seller_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('pickup_geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('delivery_geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_transport_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('CREATE INDEX IF NOT EXISTS idx_deliveries_delivery_geog ON deliveries USING gist (delivery_geog)')
    op.execute('CREATE INDEX IF NOT EXISTS idx_deliveries_pickup_geog ON deliveries USING gist (pickup_geog)')
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('raised_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.CheckConstraint("status IN ('OPEN','UNDER_REVIEW','RESOLVED','REJECTED','ESCALATED','open','under_review','resolved','closed')", name='ck_dispute_status'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_reference', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('evidence')
    op.drop_table('transaction_items')
    op.drop_table('payments')
    op.drop_table('disputes')
    op.drop_index('idx_deliveries_pickup_geog', table_name='deliveries')
    op.drop_index('idx_deliveries_delivery_geog', table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_table('transactions')
    op.drop_table('reservations')
    op.drop_table('lot_allocations')
    op.drop_table('offers')
    op.drop_table('matches')
    op.drop_index('ix_price_obs_crop_market_date', table_name='price_observations')
    op.drop_table('price_observations')
    op.drop_index('ix_lots_geog', table_name='lots')
    op.drop_index('ix_lots_public_id', table_name='lots')
    op.drop_index('ix_lots_status', table_name='lots')
    op.drop_index('ix_lots_owner', table_name='lots')
    op.drop_table('lots')
    op.drop_index('idx_buyer_requirements_location_geog', table_name='buyer_requirements')
    op.drop_table('buyer_requirements')
    op.drop_index('ix_notif_user_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('ingestion_runs')
    op.drop_table('fpo_profiles')
    op.drop_table('farmer_profiles')
    op.drop_table('crop_varieties')
    op.drop_index('idx_buyer_profiles_location_geog', table_name='buyer_profiles')
    op.drop_table('buyer_profiles')
    op.drop_index('idx_users_location_geog', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_storage_facilities_location_geog', table_name='storage_facilities')
    op.drop_table('storage_facilities')
    op.drop_table('price_sources')
    op.drop_table('match_rulesets')
    op.drop_index('ix_markets_geog', table_name='markets')
    op.drop_table('markets')
    op.drop_table('idempotency_keys')
    op.drop_table('crops')
